global:
  scrape_interval: 15s # 15초마다 데이터 수집

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' # 데이터를 가져올 경로
    static_configs:
      # 'board-app'은 docker-compose.yml의 container_name 혹은 서비스 이름이어야 함
      # 사용자님의 docker-compose.yml에 container_name: board-app 으로 되어 있으므로 아래와 같이 사용함
      - targets: ['board-app:8080']

