name: Deploy to EC@

on:
  push:
    branches:
      - main # main 브랜치에 코드가 올라오면 실행

jobs:
  deploy:
    runs-on: ubuntu_latest
    steps:
      - name: SSH로 EC2에 접속해서 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/jaebeom
            git pull origin main
            chmod +x gradlew
            ./gradlew clean build -x test
            docker compose down
            docker compose up -d --build
            docker image prune -f
